// ── Food database lookups ─────────────────────────────────────
// Local Indian food composition data (ICMR-NIN IFCT 2017 + Anuvaad INDB,
// bundled at build time — see scripts/build-indian-foods.py) plus live
// lookups against Open Food Facts (packaged foods, worldwide) and the
// USDA FoodData Central API (generic foods, worldwide).
//
// Attribution (also shown on /privacy):
// - ICMR-NIN Indian Food Composition Tables 2017
// - Anuvaad Indian Nutrient Databank (INDB)
// - Open Food Facts (ODbL) — https://world.openfoodfacts.org
// - U.S. Dept. of Agriculture, FoodData Central — https://fdc.nal.usda.gov

export interface FoodMacros {
  kcal: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
}

export interface FoodEntry {
  name: string;
  per100g: FoodMacros;
  serving?: { unit: string; grams: number };
  source: string;
  sourceUrl?: string;
}

interface IndianFoodJson {
  name: string;
  aliases?: string[];
  per100g: { kcal: number; protein: number; carbs: number; fat: number };
  serving?: { unit: string; grams: number };
  category?: string;
  source: 'INDB' | 'IFCT2017';
}

// ── Local Indian dataset ──────────────────────────────────────
let indianFoods: IndianFoodJson[] | null = null;

function loadIndianFoods(): IndianFoodJson[] {
  if (indianFoods) return indianFoods;
  try {
    // Bundled JSON generated by scripts/build-indian-foods.py
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const data = require('@/data/indian-foods.json') as {
      foods: IndianFoodJson[];
    };
    indianFoods = Array.isArray(data?.foods) ? data.foods : [];
  } catch {
    indianFoods = [];
  }
  return indianFoods;
}

const norm = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

/** Search the bundled Indian dataset. Returns best matches first. */
export function searchIndianFoods(query: string, limit = 8): FoodEntry[] {
  const foods = loadIndianFoods();
  const q = norm(query);
  if (!q || foods.length === 0) return [];
  const scored: { food: IndianFoodJson; score: number }[] = [];
  for (const f of foods) {
    const names = [f.name, ...(f.aliases ?? [])].map(norm).filter(Boolean);
    let best = 0;
    for (const n of names) {
      if (!n) continue;
      if (n === q) best = Math.max(best, 100 + n.length);
      else if (n.startsWith(q) && q.length >= 3) best = Math.max(best, 60 + q.length);
      else if (q.startsWith(n) && n.length >= 4) best = Math.max(best, 50 + n.length);
      else if (n.includes(q) && q.length >= 4) best = Math.max(best, 30 + q.length);
      else if (q.includes(n) && n.length >= 4) best = Math.max(best, 20 + n.length);
    }
    if (best > 0) scored.push({ food: f, score: best });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map(({ food: f }) => ({
    name: f.name,
    per100g: {
      kcal: f.per100g.kcal,
      proteinG: f.per100g.protein,
      carbsG: f.per100g.carbs,
      fatG: f.per100g.fat,
    },
    serving: f.serving,
    source: f.source === 'INDB' ? 'Anuvaad INDB' : 'ICMR-NIN IFCT 2017',
  }));
}

// ── Free-text → database estimate (used by /api/parse-meal) ───
const PART_SPLIT = /\s+(?:and|with|plus|&)\s+|\s*[,+]\s*/i;

const SERVING_WORDS = new Set([
  'bowl', 'bowls', 'plate', 'plates', 'cup', 'cups', 'katori', 'katoris',
  'piece', 'pieces', 'slice', 'slices', 'glass', 'glasses', 'serving', 'servings',
]);

/** Candidate word forms: as-is, de-pluralized, and common Hindi plural variants. */
function wordForms(w: string): string[] {
  const forms = [w];
  if (w.length > 3 && w.endsWith('s') && !w.endsWith('ss')) forms.push(w.slice(0, -1));
  if (w.length > 4 && w.endsWith('es')) forms.push(w.slice(0, -2));
  if (w.length > 4 && w.endsWith('e')) forms.push(`${w.slice(0, -1)}a`); // bhature → bhatura
  return [...new Set(forms)];
}

function matchFoodInPart(part: string): IndianFoodJson | null {
  const foods = loadIndianFoods();
  if (foods.length === 0) return null;
  const words = norm(part)
    .split(' ')
    .filter((w) => w && !SERVING_WORDS.has(w));
  if (words.length === 0) return null;
  const p = ` ${words.join(' ')} `;
  const variants = words.map(wordForms);

  // Generic shorthand → the most representative dish (plain home-style).
  // Checked against all word variants so "rotis" hits the "roti" key.
  const GENERIC_FALLBACK: Record<string, string> = {
    dal: 'Dal moong',
    roti: 'Chapati/Roti',
    rice: 'Boiled rice',
    chawal: 'Boiled rice',
  };
  if (words.length === 1) {
    const key = variants[0].find((v) => GENERIC_FALLBACK[v]);
    if (key) {
      const hit = foods.find((f) => norm(f.name) === norm(GENERIC_FALLBACK[key]));
      if (hit) return hit;
    }
  }

  // Tier 1: full name/alias appears as whole words in the part.
  // Collect every candidate, longest match first — then keep the first one
  // that also passes the coverage guard below (a long coincidental alias
  // hit must not shadow a shorter correct one).
  const candidates: { food: IndianFoodJson; matchLen: number }[] = [];
  for (const f of foods) {
    const names = [f.name, ...(f.aliases ?? [])].map(norm).filter((n) => n.length >= 3);
    let ml = 0;
    for (const n of names) {
      if (p.includes(` ${n} `) && n.length > ml) ml = n.length;
    }
    if (ml > 0) candidates.push({ food: f, matchLen: ml });
  }
  candidates.sort((a, b) => b.matchLen - a.matchLen);
  // Tier 2: single content word equals a word in the food name
  // (e.g. "paratha" → "Aloo paratha"). Prefer the shortest (most generic) name.
  if (candidates.length === 0 && words.length === 1) {
    const forms = variants[0];
    let shortest: IndianFoodJson | null = null;
    for (const f of foods) {
      const nameWords = norm(f.name).split(' ');
      if (nameWords.some((nw) => forms.includes(nw))) {
        if (!shortest || f.name.length < shortest.name.length) shortest = f;
      }
    }
    if (shortest) candidates.push({ food: shortest, matchLen: 99 });
  }
  if (candidates.length === 0) return null;
  // Coverage guard: the match must account for MORE than half the part's
  // content words — otherwise it's a coincidental alias hit (e.g. "chole"
  // matching a chickpea roti inside "chole bhature"). Let the AI handle those.
  for (const { food: best } of candidates) {
    const matchedWords = new Set(
      [best.name, ...(best.aliases ?? [])].map(norm).join(' ').split(' ').flatMap(wordForms),
    );
    const covered = words.filter((w) => wordForms(w).some((v) => matchedWords.has(v))).length;
    if (covered * 2 > words.length) return best;
  }
  return null;
}

function parseQuantity(part: string): { qty: number; grams: number | null; rest: string } {
  let rest = part.trim();
  let qty = 1;
  const numMatch = rest.match(/^(\d+(?:\.\d+)?)\s*(?:x|×)?\s+/);
  if (numMatch) {
    qty = parseFloat(numMatch[1]);
    rest = rest.slice(numMatch[0].length);
  } else if (/^(a|an|one)\s+/i.test(rest)) {
    rest = rest.replace(/^(a|an|one)\s+/i, '');
  }
  const gMatch = rest.match(/(\d+(?:\.\d+)?)\s*g(?:rams?)?\b/i);
  const grams = gMatch ? parseFloat(gMatch[1]) : null;
  return { qty, grams, rest };
}

/**
 * Try to estimate a meal purely from the bundled Indian food database.
 * Handles multi-part descriptions ("2 rotis and dal") — every part must
 * match, otherwise returns null so the AI estimator can take over.
 */
export function estimateFromDb(text: string): { meal: { name: string; calories: number; proteinG: number; carbsG: number; fatG: number }; source: string } | null {
  const parts = text.split(PART_SPLIT).map((s) => s.trim()).filter(Boolean);
  if (parts.length === 0 || parts.length > 4) return null;

  let kcal = 0, protein = 0, carbs = 0, fat = 0;
  const names: string[] = [];
  let source = '';

  for (const part of parts) {
    const { qty, grams, rest } = parseQuantity(part);
    const food = matchFoodInPart(rest);
    if (!food) return null;
    const g = grams ?? (food.serving ? food.serving.grams * qty : 150);
    const f = g / 100;
    kcal += food.per100g.kcal * f;
    protein += food.per100g.protein * f;
    carbs += food.per100g.carbs * f;
    fat += food.per100g.fat * f;
    names.push(qty > 1 ? `${qty} ${food.name}` : food.name);
    source = food.source === 'INDB' ? 'Anuvaad INDB' : 'ICMR-NIN IFCT 2017';
  }

  const r1 = (n: number) => Math.round(n * 10) / 10;
  return {
    meal: {
      name: names.join(' + ').slice(0, 80),
      calories: Math.min(2500, Math.round(kcal)),
      proteinG: r1(protein),
      carbsG: r1(carbs),
      fatG: r1(fat),
    },
    source,
  };
}

// ── Open Food Facts (live) ────────────────────────────────────
const OFF_UA = 'Zaiq/1.0 (https://diet-asisstant-app.vercel.app; nutrition lookup)';
const offCache = new Map<string, { at: number; entry: FoodEntry | null }>();

function nutrimentsToMacros(n: Record<string, number | undefined>): FoodMacros | null {
  const kcal = n['energy-kcal_100g'];
  if (!Number.isFinite(kcal)) return null;
  return {
    kcal: Math.round(kcal as number),
    proteinG: Math.round(((n['proteins_100g'] as number) || 0) * 10) / 10,
    carbsG: Math.round(((n['carbohydrates_100g'] as number) || 0) * 10) / 10,
    fatG: Math.round(((n['fat_100g'] as number) || 0) * 10) / 10,
  };
}

/** Barcode lookup via Open Food Facts. Cached in-memory for 24h. */
export async function lookupBarcode(barcode: string): Promise<FoodEntry | null> {
  const code = barcode.replace(/\D/g, '');
  if (!code) return null;
  const hit = offCache.get(code);
  if (hit && Date.now() - hit.at < 24 * 3600 * 1000) return hit.entry;
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), 12000);
    const res = await fetch(`https://world.openfoodfacts.org/api/v3/product/${code}.json`, {
      headers: { 'User-Agent': OFF_UA },
      signal: ctrl.signal,
    });
    clearTimeout(t);
    if (!res.ok) {
      offCache.set(code, { at: Date.now(), entry: null });
      return null;
    }
    const data = (await res.json()) as {
      product?: {
        product_name?: string; brands?: string;
        nutriments?: Record<string, number>; code?: string;
        serving_size?: string; quantity?: string;
      };
    };
    const p = data?.product;
    const macros = p?.nutriments ? nutrimentsToMacros(p.nutriments) : null;
    // Prefer the label's serving size ("70g", "30 g") so logging defaults
    // to one pack/serving instead of a full 100g.
    let servingG: number | null = null;
    const servingStr = p?.serving_size || '';
    const m = servingStr.match(/([\d.]+)\s*g/i);
    if (m) servingG = parseFloat(m[1]);
    const entry: FoodEntry | null =
      p && macros
        ? {
            name: [p.brands, p.product_name].filter(Boolean).join(' ').slice(0, 80) || `Product ${code}`,
            per100g: macros,
            serving: servingG ? { unit: 'serving', grams: servingG } : undefined,
            source: 'Open Food Facts',
            sourceUrl: `https://world.openfoodfacts.org/product/${code}`,
          }
        : null;
    offCache.set(code, { at: Date.now(), entry });
    return entry;
  } catch {
    return null;
  }
}

/** Text search via Open Food Facts (packaged foods, worldwide). */
export async function searchOpenFoodFacts(query: string, limit = 5): Promise<FoodEntry[]> {
  const q = query.trim();
  if (!q) return [];
  // v2 structured search has been flaky ("Page temporarily unavailable"),
  // so use the search index for candidate barcodes, then fetch each
  // product's v3 record for its nutriments.
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), 12000);
    const res = await fetch(
      `https://search.openfoodfacts.org/search?q=${encodeURIComponent(q)}&page_size=${limit}`,
      { headers: { 'User-Agent': OFF_UA }, signal: ctrl.signal },
    );
    clearTimeout(t);
    if (!res.ok) return [];
    const data = (await res.json()) as { hits?: { code?: string }[] };
    const codes = [...new Set((data?.hits ?? []).map((h) => String(h?.code || '')).filter(Boolean))].slice(0, 3);
    const out: FoodEntry[] = [];
    for (const code of codes) {
      const entry = await lookupBarcode(code);
      if (entry) out.push(entry);
    }
    return out;
  } catch {
    return [];
  }
}

// ── USDA FoodData Central (live) ──────────────────────────────
const usdaCache = new Map<string, { at: number; entries: FoodEntry[] }>();

function usdaNutrientsToMacros(nutrients: { nutrientName: string; unitName: string; value: number }[]): FoodMacros | null {
  let kcal = 0, protein = 0, carbs = 0, fat = 0, haveKcal = false;
  for (const n of nutrients ?? []) {
    const name = (n.nutrientName || '').toLowerCase();
    const v = Number(n.value) || 0;
    if (name === 'energy' && n.unitName === 'KCAL') { kcal = v; haveKcal = true; }
    else if (name === 'protein') protein = v;
    else if (name.includes('carbohydrate')) carbs = v;
    else if (name.includes('total lipid')) fat = v;
  }
  if (!haveKcal) return null;
  const r1 = (x: number) => Math.round(x * 10) / 10;
  return { kcal: Math.round(kcal), proteinG: r1(protein), carbsG: r1(carbs), fatG: r1(fat) };
}

/** Generic food search via USDA FoodData Central. Needs USDA_FDC_API_KEY env (falls back to DEMO_KEY, heavily rate-limited). */
export async function searchUsda(query: string, limit = 5): Promise<FoodEntry[]> {
  const q = query.trim();
  if (!q) return [];
  const key = (process.env.USDA_FDC_API_KEY || 'DEMO_KEY').trim();
  const cacheKey = `${key === 'DEMO_KEY' ? 'demo' : 'k'}:${q.toLowerCase()}`;
  const hit = usdaCache.get(cacheKey);
  if (hit && Date.now() - hit.at < 24 * 3600 * 1000) return hit.entries;
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), 12000);
    const url =
      `https://api.nal.usda.gov/fdc/v1/foods/search?query=${encodeURIComponent(q)}` +
      `&dataType=Foundation,SR%20Legacy&pageSize=${limit}&api_key=${encodeURIComponent(key)}`;
    const res = await fetch(url, { signal: ctrl.signal });
    clearTimeout(t);
    if (!res.ok) return [];
    const data = (await res.json()) as {
      foods?: { description?: string; foodNutrients?: { nutrientName: string; unitName: string; value: number }[]; fdcId?: number }[];
    };
    const out: FoodEntry[] = [];
    for (const f of data?.foods ?? []) {
      const macros = f?.foodNutrients ? usdaNutrientsToMacros(f.foodNutrients) : null;
      if (!macros) continue;
      out.push({
        name: (f.description || '').toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase()).slice(0, 80) || 'Unknown food',
        per100g: macros,
        source: 'USDA FoodData Central',
        sourceUrl: f.fdcId ? `https://fdc.nal.usda.gov/food-details/${f.fdcId}/nutrients` : undefined,
      });
    }
    usdaCache.set(cacheKey, { at: Date.now(), entries: out });
    return out;
  } catch {
    return [];
  }
}

export const FOOD_DB_ATTRIBUTION =
  'Nutrition data: ICMR-NIN Indian Food Composition Tables 2017, Anuvaad Indian Nutrient Databank, Open Food Facts (ODbL), USDA FoodData Central.';
